import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Categories, PostCard, PostWidget } from "../Components";
import { getPosts } from "../Services";
export default function Home({ posts }) {
  console.log(posts[0].node);
  return (
    <div className="container mx-auto px-10 mb-8 bg-gray-100">
      <Head>
        <title>SH BLOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-8 col-span-1">
          {posts.map((data) => (
            <PostCard post={data.node} key={new Date()} />
          ))}
        </div>
        <div className="lg:col-span-4 col-span-1">
          <div className="lg:sticky relative top-8">
            <PostWidget />
            <Categories />
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const posts = await getPosts();
  return {
    props: {
      posts,
    },
  };
}
